### ISSUE TITLE
Parse an uploaded csv to check for reminders and events

### ISSUE THREAD

**Issue by qchen59** [qchen59/TeachersPetBot#6]
From TeachersPetBot created by [salvisumedh2396](https://github.com/salvisumedh2396): War-Keeper/TeachersPetBot#30  

null

**Comment by hughman98** [comment]
This was resolved with PR #30 

To summarize, a lot of the work here was already done by the previous group, although they didn't update this issue. What we did was finish what they started as far as reading the events goes, and also update the names/flows within the program so that they work more intuitively. For example, with how the previous group was planning on setting this up you had to include a file as a reply with your initial request, which I changed.
